### PR TITLE
Fixed #7630

### LINKED ISSUE #7630: [gitdev v4.4.x] Wrong calculation in quotes
#### Issue

In "My Preferences" we use a "," as Decimal seperator and "." for the digit grouping seperator. Now we have the problem, that when we add a service "Consulting" in Days, then the price is calculated incorrectly when we add half days. With the standard Setting (look at screenshots) it works correctly!

#### Actual Behavior

quote nok cust
quote nok 1

#### Expected Behavior

quote ok cust
quote ok 1

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: gitdeveloper v 4.4.14 or new installation v4.4.0
* Browser name and version: chrome
* Environment name and version: WAMP / gitdeveloper
* Operating System and version: Windows 10 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/62065014-gitdev-v4-4-x-wrong-calculation-in-quotes?utm_campaign=plugin&utm_content=tracker%2F9760560&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F9760560&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by slawekk87**
## Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code is written according to the guidelines found [here] (https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/how-to-create-php-files).
- [ ] I have signed the Contributor Licence Agreement between me and YetiForce.

### CODE REVIEW

File: modules/Vtiger/inventoryfields/Quantity.php [hunk 1]
```diff
@@ -29,7 +29,7 @@ class Vtiger_Quantity_InventoryField extends Vtiger_Basic_InventoryField
 	 */
 	public function getDisplayValue($value, $rawText = false)
 	{
-		return \App\Purifier::encodeHtml(vtlib\Functions::formatDecimal($value));
+		return \App\Purifier::encodeHtml(\App\Fields\Currency::formatToDisplay($value));
```
Comment (rskrzypczak) [inline modules/Vtiger/inventoryfields/Quantity.php]:
```suggestion
		return \App\Purifier::encodeHtml(\App\Fields\Currency::formatToDisplay($value, null, true));
```
