### PR TITLE
Fixed #13326

### LINKED ISSUE #13326: [bug] Calendar widget shows wrong starttime
Hello,

I configured a litte widget to have a list of my tasks, appointments, etc. on my dashbord.
I discoverd now, that the starting time of every item is shown with 00:00, but when you mouseover the item the correct startingtime is shown.

Screenshot_2020-07-20 Meine Startseite

MyCalendar

Any ideas? Thanks!

### PR DESCRIPTION
**Pull request by areksolek**
image

### CODE REVIEW

File: modules/Vtiger/models/MiniList.php [hunk 1]
```diff
@@ -54,12 +54,21 @@ public function getTargetModule()
...
 		$fields = $this->extraData['fields'];
+		$moduleName = $this->getTargetModule();
 		if (!\in_array('id', $fields)) {
 			$fields[] = 'id';
 		}
+		if ('Calendar' === $moduleName && $extraField) {
+			$moduleModel = \Vtiger_Module_Model::getInstance($moduleName);
+			if (\in_array('date_start', $fields) && ($fieldModel = \Vtiger_Field_Model::getInstance('time_start', $moduleModel)) && $fieldModel->isActiveField() && $fieldModel->isViewable()) {
+				$fields[] = 'time_start';
+			} elseif (\in_array('due_end', $fields) && ($fieldModel = \Vtiger_Field_Model::getInstance('time_end', $moduleModel)) && $fieldModel->isActiveField() && $fieldModel->isViewable()) {
```
Comment (rskrzypczak) [inline modules/Vtiger/models/MiniList.php]: You cannot use elseif
```suggestion
			}
			if (\in_array('due_end', $fields) && ($fieldModel = \Vtiger_Field_Model::getInstance('time_end', $moduleModel)) && $fieldModel->isActiveField() && $fieldModel->isViewable()) {
```

File: modules/Vtiger/models/MiniList.php [hunk 2]
```diff
@@ -54,12 +54,22 @@ public function getTargetModule()
...
-	public function getTargetFields()
+	public function getTargetFields($extraField = false)
 	{
 		$fields = $this->extraData['fields'];
+		$moduleName = $this->getTargetModule();
 		if (!\in_array('id', $fields)) {
 			$fields[] = 'id';
 		}
+		if ('Calendar' === $moduleName && $extraField) {
+			$moduleModel = \Vtiger_Module_Model::getInstance($moduleName);
```
Comment (rskrzypczak) [inline modules/Vtiger/models/MiniList.php]:
```suggestion
			$moduleModel = $this->getTargetModuleModel();
```

File: modules/Vtiger/models/MiniList.php [hunk 3]
```diff
@@ -102,8 +112,10 @@ public function getHeaders()
 		$this->initListViewController();
 		if (!$this->listviewHeaders) {
 			$headerFieldModels = [];
-			foreach ($this->queryGenerator->getListViewFields() as $fieldName => &$fieldsModel) {
-				$headerFieldModels[$fieldName] = $fieldsModel;
+			foreach ($this->getTargetFields() as $fieldName) {
+				if ('id' !== $fieldName) {
+					$headerFieldModels[$fieldName] = \Vtiger_Field_Model::getInstance($fieldName, \Vtiger_Module_Model::getInstance($this->getTargetModule()));
```
Comment (rskrzypczak) [inline modules/Vtiger/models/MiniList.php]:
```suggestion
					$headerFieldModels[$fieldName] = $this->getTargetModuleModel()->getFieldByName($fieldName);
```
