### PR TITLE
Fixed #17252

### LINKED ISSUE #17252: [bug] Dashboard Chart Widget Tabular Link not
Hi,

I faced issue on my local server, then I replicated on https://gitstable.yetiforce.com/index.php and found same issue, below is from https://gitstable.yetiforce.com

I have created Dashboard Widget with Chart from Filter, selected Tickets by Date, and below details

image

after this dashboard is visible as below
image

When I click on number link 
image

I get Incorrect Request Error as below
image

On further study I noticed that URL generated is as below
https://gitstable.yetiforce.com/index.php?module=HelpDesk&view=List&viewname=153&search_params=%5B%5B%5B%22closing_datatime%22%2C%22e%22%2C%222023-07-22%2005%3A00%3A00%22%5D%5D%5D

where as If I change date format from yyyy-mm-dd to mm-dd-yyyy then URL works properly.
https://gitstable.yetiforce.com/index.php?module=HelpDesk&view=List&viewname=153&search_params=%5B%5B%5B%22closing_datatime%22%2C%22e%22%2C%2207-22-2023%2005%3A00%3A00%22%5D%5D%5D

There seems to be issue with locale formatting of date

Please see the problem

### PR DESCRIPTION
**Pull request by areksolek**
Fixed #17252

### CODE REVIEW

File: modules/Vtiger/models/ChartFilter.php [hunk 1]
```diff
@@ -1286,6 +1286,8 @@ protected function getSearchParamValue(Vtiger_Field_Model $fieldModel, $value):
 		} elseif (\in_array($fieldDataType, ['multipicklist', 'categoryMultipicklist'])) {
 			$operator = 'c';
 			$value = 'multipicklist' === $fieldDataType ? str_replace(' |##| ', '##', $value) : $value;
+		} elseif (\in_array($fieldDataType, ['date', 'datetime'])) {
+			$value = DateTimeField::convertToUserFormat($value);
```
Comment (rskrzypczak) [inline modules/Vtiger/models/ChartFilter.php]: does not support 12 hour time mode

File: modules/Vtiger/models/ChartFilter.php [hunk 2]
```diff
@@ -1286,6 +1286,8 @@ protected function getSearchParamValue(Vtiger_Field_Model $fieldModel, $value):
 		} elseif (\in_array($fieldDataType, ['multipicklist', 'categoryMultipicklist'])) {
 			$operator = 'c';
 			$value = 'multipicklist' === $fieldDataType ? str_replace(' |##| ', '##', $value) : $value;
+		} elseif (\in_array($fieldDataType, ['date', 'datetime'])) {
```
Comment (rskrzypczak) [inline modules/Vtiger/models/ChartFilter.php]: two elseif

File: modules/Vtiger/models/ChartFilter.php [hunk 3]
```diff
@@ -1286,10 +1286,11 @@ protected function getSearchParamValue(Vtiger_Field_Model $fieldModel, $value):
 		} elseif (\in_array($fieldDataType, ['multipicklist', 'categoryMultipicklist'])) {
 			$operator = 'c';
 			$value = 'multipicklist' === $fieldDataType ? str_replace(' |##| ', '##', $value) : $value;
-		} elseif (\in_array($fieldDataType, ['date', 'datetime'])) {
-			$value = 'datetime' === $fieldDataType ? App\Fields\DateTime::formatToDisplay($value) : App\Fields\Date::formatToDisplay($value);
+		} elseif ('date' === $fieldDataType) {
+			$value = App\Fields\Date::formatToDisplay($value);
+		} elseif ('datetime' === $fieldDataType) {
+			$value =App\Fields\DateTime::formatToDisplay($value);
```
Comment (rskrzypczak) [inline modules/Vtiger/models/ChartFilter.php]: formatting
