### PR TITLE
Fixed #12787

### LINKED ISSUE #12787: [bug] Project Task widgets
# 🐞 bug report

Good evening.
I have detected a bug in the task widghet that is displayed in the project summary. The filter does not work and if active the private makes all the details of the summary disappear. I also tried it on https://gitdeveloper.yetiforce.com/ and found the same problems. I attach gif.

### 🔥 How to trigger the error

task widgets

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [v] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### PR DESCRIPTION
**Pull request by areksolek**
projectWidget

### CODE REVIEW

File: public_html/layouts/basic/modules/Vtiger/resources/Detail.js [hunk 1]
```diff
@@ -1627,7 +1627,7 @@ jQuery.Class(
 			});
 			var urlNewParams = [];
 			summaryWidgetContainer
-				.find('.js-switch, .js-detail-widget-header .js-filter_field')
+				.find('.js-switch, .js-detail-widget-header, .js-filter_field')
```
Comment (rskrzypczak) [inline public_html/layouts/basic/modules/Vtiger/resources/Detail.js]: revert

File: layouts/basic/modules/Vtiger/Detail/Widget/Basic.tpl [hunk 2]
```diff
@@ -86,6 +86,7 @@
 				{else}
 					{assign var=span value='col-12'}
 				{/if}
+				{assign var=RELATED_MODULE_MODEL value=Vtiger_Module_Model::getInstance($RELATED_MODULE_NAME)}
```
Comment (rskrzypczak) [inline layouts/basic/modules/Vtiger/Detail/Widget/Basic.tpl:89]: duplicate

**Review by rskrzypczak — CHANGES_REQUESTED** [review]

File: layouts/basic/modules/Vtiger/Detail/Widget/Basic.tpl (hunk 2 above)
Comment (areksolek) [reply layouts/basic/modules/Vtiger/Detail/Widget/Basic.tpl:89]: the duplicate has been removed

**Review by mariuszkrzaczkowski — APPROVED** [review]
