### PR TITLE
#10612 fix

### LINKED ISSUE #10612: [bug] lineitem: reference field resets name field
# 🐞 bug report
if you add a reference field to lineitem, select and reset actions affect lineitem name field too
 
### 🔥 How to trigger the error
lineitemreference

### 👎 Actual Behavior
reference field to lineitem actions affect lineitem name field

### 👍 Expected Behavior
actions on reference field affect only reference field

### 📷 Screenshot of configuration
[none]

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
[independent]

### 🌍  Your Environment 
[independent]

### ❓ Additional context
[none]

### :heavy_check_mark: Fix
/public_html/layouts/basic/modules/Vtiger/resources/Inventory.js: 1358
registerClearReferenceSelection() {...}

```code
registerClearReferenceSelection() {
  this.form.on('click', '.clearReferenceSelection', e => {
    const referenceGroup = $(e.currentTarget).closest('div.referenceGroup');
// ===>> check if reference field type: not lineitem name
    if(referenceGroup.length) {
// ===>> reset only reference field: display and value
      referenceGroup.find('input[id$="_display"]').val('').removeAttr('readonly');
    } else {
      const row = this.getClosestRow($(e.currentTarget));
      this.removeSubProducts(row);
      row.find('.unitPrice,.tax,.discount,.margin,.purchase,.js-tax-percent').val(App.Fields.Double.formatToDisplay(0));
      row.find('.qty').val(1);
      row.find('textarea,.valueVal').val('');
      row.find('.valueText').text('');
      row.find('.qtyParamInfo').addClass('d-none');
      row.find('.recordLabel').val('').removeAttr('readonly');
      if (!this.isGroupTaxMode()) {
        this.setTaxParam(row, []);
      }
      this.quantityChangeActions(row);
    }
  });
},

```

### PR DESCRIPTION
**Pull request by davide-alghi**
add reference field type check
(better indented code)

fix #10612 issue

### CODE REVIEW

File: public_html/layouts/basic/modules/Vtiger/resources/Inventory.js [hunk 1]
```diff
@@ -1475,23 +1475,22 @@ $.Class(
...
-				row.find('textarea,.valueVal').val('');
-				row.find('.valueText').text('');
-				row.find('.qtyParamInfo').addClass('d-none');
-				row
-					.find('.recordLabel')
-					.val('')
-					.removeAttr('readonly');
-				if (!this.isGroupTaxMode()) {
-					this.setTaxParam(row, []);
+				if(referenceGroup.length) {
```
Comment (rskrzypczak) [inline public_html/layouts/basic/modules/Vtiger/resources/Inventory.js]: Undefined variable 'referenceGroup'

Comment (davide-alghi) [reply public_html/layouts/basic/modules/Vtiger/resources/Inventory.js]: lost in copying ... added referenceGroup var
