### PR TITLE
Fixed password detail view, improved modTracker when showing hidden data

### LINKED ISSUE #12032: [bug] password review history not working
#11225 🐞 bug report

### ⁉️ Describe the bug
The view History (Modtracker?) is not updated when a password is shown from an account.

### 🔥 How to trigger the error
1. Go to https://gitstable.yetiforce.com/index.php?module=OSSPasswords&view=Detail&record=3137&mode=showRecentActivities&page=1&tab_label=LBL_UPDATES&whereCondition=review
2. Press F5
3. YEP, we got an Update on the view history
4. https://gitstable.yetiforce.com/index.php?module=Accounts&relatedModule=OSSPasswords&view=Detail&record=227&mode=showRelatedList&tab_label=OSSPasswords
5. click on "show password"
6. NOPE no update in the modtracker

### 👎 Actual Behavior
See 6 above

### 👍 Expected Behavior
Modtracker Update? Espacially for password... Security issue?

### 👷 Testing 
- [ X] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ X] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### PR DESCRIPTION
**Pull request by adudekyeti**

### CODE REVIEW

File: modules/ModTracker/models/Record.php [hunk 1]
```diff
@@ -481,10 +493,10 @@ public static function getConditionByType($type)
 		$where = [];
 		switch ($type) {
 			case 'changes':
-				$where = ['<>', 'status', self::DISPLAYED];
+				$where = ['and', ['<>', 'status', self::DISPLAYED], ['!=', 'status', self::SHOW_HIDDEN_DATA]];
```
Comment (mariuszkrzaczkowski) [inline modules/ModTracker/models/Record.php]:
```suggestion
				$where = ['not in', 'status', [self::DISPLAYED, self::SHOW_HIDDEN_DATA]];
```

**Review by mariuszkrzaczkowski — CHANGES_REQUESTED** [review]

**Review by mariuszkrzaczkowski — APPROVED** [review]
